service: smeedies-maritime-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'prod'}
  region: us-east-1
  environment:
    NODE_ENV: production
    DYNAMODB_TABLE_NAME: ${env:DYNAMODB_TABLE_NAME, 'smeedies-maritime-messages'}
    DYNAMODB_ADMIN_TABLE_NAME: ${env:DYNAMODB_ADMIN_TABLE_NAME, 'smeedies-maritime-admin-users'}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    SESSION_SECRET: ${env:SESSION_SECRET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - dynamodb:Query
          Resource: 
            - "arn:aws:dynamodb:${self:provider.region}:*:table/smeedies-maritime-messages"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/smeedies-maritime-admin-users"

functions:
  chatbot:
    handler: lambda/chatbot.handler
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: chatbot/{proxy+}
          method: ANY
          cors: true
  
  contact:
    handler: lambda/contact.handler
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: contact
          method: POST
          cors: true
  
  admin:
    handler: lambda/admin.handler
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: admin/{proxy+}
          method: ANY
          cors: true
  
  health:
    handler: lambda/health.handler
    timeout: 10
    memorySize: 128
    events:
      - http:
          path: health
          method: GET
          cors: true

# plugins:
#   - serverless-offline

# custom:
#   serverless-offline:
#     httpPort: 3000
#     host: 0.0.0.0

package:
  patterns:
    - '!node_modules/**'
    - '!package-lock.json'
    - '!*.md'
    - '!.git/**'
    - '!.cursor/**'
    - '!.vscode/**'
    - '!.serverless/**'
    - '!.local/**'
    - '!.playwright-mcp/**'
    - '!.env'
    - '!client/**'
    - '!server/**'
    - '!shared/**'
    - '!static-build/**'
    - '!dist/**'
    - '!scripts/**'
    - '!attached_assets/**'
    - '!*.css'
    - '!*.html'
    - '!*.json'
    - '!*.txt'
    - '!*.zip'
    - '!*.png'
    - '!*.jpg'
    - '!*.jpeg'
    - '!*.gif'
    - '!*.svg'
    - '!*.ico'
    - '!amplify.yml'
    - '!.amplifyrc'
    - '!DETAILED_MODEL_ANALYSIS.md'
    - '!MODERN_HERO_DESIGN.md'
    - '!SHIPPING_ROUTES.md'
    - '!DEPLOYMENT_GUIDE.md'
    - '!AMPLIFY_CHECKLIST.md'
    - '!tailwind.config.js'
    - '!postcss.config.js'
    - '!vite.config.ts'
    - '!vite.static.config.ts'
    - '!components.json'
    - '!drizzle.config.ts'
    - '!tsconfig.json'
